services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3:3.83.2
    ports:
      - '8081:8081'
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G

  devcontainer:
    image: telenity/devcontainer/react:latest
    container_name: devcontainer
    command: tail -f /dev/null
    volumes:
      - ..:/workspace:cached
